
path: C:\Users\mtiurina\source\repos\airo\DataSets\otolith_cuts_marks_1280_labeled
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: mark
  1: otolith